// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA0IwV42ZAFk9us9FjypM1xstSmPCPAMCs',
    appId: '1:448569975456:web:a473dee3e06c0c3dc8dfc5',
    messagingSenderId: '448569975456',
    projectId: 'project-b4412',
    authDomain: 'project-b4412.firebaseapp.com',
    storageBucket: 'project-b4412.firebasestorage.app',
    measurementId: 'G-4ZS5BGDC0M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAkVpGoa0S31cWzkyBC9yakLo_SeRkTavs',
    appId: '1:448569975456:android:45a5c5d583a71cd7c8dfc5',
    messagingSenderId: '448569975456',
    projectId: 'project-b4412',
    storageBucket: 'project-b4412.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCGohDj8BthPlv8KNiCIRzNrtPWD39jTEk',
    appId: '1:448569975456:ios:88d1ebf1ddd50376c8dfc5',
    messagingSenderId: '448569975456',
    projectId: 'project-b4412',
    storageBucket: 'project-b4412.firebasestorage.app',
    iosBundleId: 'com.example.task9',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCGohDj8BthPlv8KNiCIRzNrtPWD39jTEk',
    appId: '1:448569975456:ios:88d1ebf1ddd50376c8dfc5',
    messagingSenderId: '448569975456',
    projectId: 'project-b4412',
    storageBucket: 'project-b4412.firebasestorage.app',
    iosBundleId: 'com.example.task9',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA0IwV42ZAFk9us9FjypM1xstSmPCPAMCs',
    appId: '1:448569975456:web:4a757a6c5eacb564c8dfc5',
    messagingSenderId: '448569975456',
    projectId: 'project-b4412',
    authDomain: 'project-b4412.firebaseapp.com',
    storageBucket: 'project-b4412.firebasestorage.app',
    measurementId: 'G-6G8FPH9NG2',
  );
}
